#!/bin/bash

set -e

test $# = 1 && set -- "$1"/*
test $# = 0 && set -- *

function main {
  for filename in "$@"; do
    if test -d "$filename/.git"; then
      examine-directory "$filename"
    fi
  done

  if test -z "$any_output"; then
    if test -n "$n_clean"; then
      echo "$n_clean clean repositories"
    else
      echo "No repositories here"
    fi
  fi
}

function examine-directory {
  status=`cd "$1" && git -c color.status=always status -b --short 2>&1`
  if is-status-interesting "$status"; then
    print-status "$1" "$status"
  else
    ((n_clean+=1))
  fi
}

function is-status-interesting {
  echo "$1" | grep -qv -E '^## [^ ]+$'
}

function print-status {
  test -n "$any_output" && echo || any_output=yes
  echo "$1:"
  echo "$2"
}

main "$@"
