#!/bin/bash

test $# = 0 && set -- ..
test $# = 1 && set -- "$1"/*

function main {
  for directory in "$@"; do examine-repository "$directory"; done
  test -n "$any_output" || echo "$# clean repositories"
}

function examine-repository {
  status=`get-status "$1"`
  is-status-interesting "$status" && print-status "$1" "$status"
}

function get-status {
  (cd "$1" && git -c color.status=always status -b --short 2>&1);
}

function is-status-interesting {
  echo "$1" | grep -qv -E '^## [^ ]+$';
}

function print-status {
  test -n "$any_output" && echo || any_output=yes
  echo "$1:"
  echo "$2"
}

main "$@"
